package com.dynamodb.dto;

import java.util.List;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.fasterxml.jackson.annotation.JsonProperty;

@DynamoDBTable(tableName = "movie")
public class Movie {

	String filmId;

	String title;

	String releaseYear;

	String rated;

	String released;

	String runtime;

	List<String> genres;

	List<String> actors;

	String director;

	String plot;

	String language;

	String country;

	String awards;

	String imdbRating;

	@DynamoDBHashKey(attributeName = "FilmId")
	@DynamoDBAutoGeneratedKey
	@JsonProperty("FilmId")
	public String getFilmId() {
		return filmId;
	}

	public void setFilmId(String filmId) {
		this.filmId = filmId;
	}

	@DynamoDBAttribute(attributeName = "Title")
	@JsonProperty("Title")
	public String getTitle() {
		return title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@DynamoDBAttribute(attributeName = "Year")
	@JsonProperty("Year")
	public String getReleaseYear() {
		return releaseYear;
	}

	public void setReleaseYear(String releaseYear) {
		this.releaseYear = releaseYear;
	}

	@DynamoDBAttribute(attributeName = "Rated")
	@JsonProperty("Rated")
	public String getRated() {
		return rated;
	}

	public void setRated(String rated) {
		this.rated = rated;
	}

	@DynamoDBAttribute(attributeName = "Released")
	@JsonProperty("Released")
	public String getReleased() {
		return released;
	}

	public void setReleased(String released) {
		this.released = released;
	}

	@DynamoDBAttribute(attributeName = "Runtime")
	@JsonProperty("Runtime")
	public String getRuntime() {
		return runtime;
	}

	public void setRuntime(String runtime) {
		this.runtime = runtime;
	}

	@DynamoDBAttribute(attributeName = "Actors")
	@JsonProperty("Actors")
	public List<String> getActors() {
		return actors;
	}

	public void setActors(List<String> actors) {
		this.actors = actors;
	}

	@DynamoDBAttribute(attributeName = "Director")
	@JsonProperty("Director")
	public String getDirector() {
		return director;
	}

	public void setDirector(String director) {
		this.director = director;
	}

	@DynamoDBAttribute(attributeName = "Plot")
	@JsonProperty("Plot")
	public String getPlot() {
		return plot;
	}

	public void setPlot(String plot) {
		this.plot = plot;
	}

	@DynamoDBAttribute(attributeName = "Language")
	@JsonProperty("Language")
	public String getLanguage() {
		return language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@DynamoDBAttribute(attributeName = "Country")
	@JsonProperty("Country")
	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@DynamoDBAttribute(attributeName = "Awards")
	@JsonProperty("Awards")
	public String getAwards() {
		return awards;
	}

	public void setAwards(String awards) {
		this.awards = awards;
	}

	@DynamoDBAttribute(attributeName = "imdbRating")
	@JsonProperty("imdbRating")
	public String getImdbRating() {
		return imdbRating;
	}

	public void setImdbRating(String imdbRating) {
		this.imdbRating = imdbRating;
	}

	@DynamoDBAttribute(attributeName = "Genre")
	@JsonProperty("Genre")
	public List<String> getGenres() {
		return genres;
	}

	public void setGenres(List<String> genres) {
		this.genres = genres;
	}

}
