
aws:
  access-key: ${AWS_ACCESS_KEY}
  secret-key: ${AWS_SECRET_KEY}
  dynamodb:
    #endpoint: "http://localhost:8000"
   
cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-2
#Access Key:AKIAJMMYMHBAO2QUZVKQ
#Secret Access Key: 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

spring:
  data:
    dynamodb:
      entity2ddl:
        auto: validate
  main:
    allow-circular-references: true

